<a href="https://colab.research.google.com/github/poonampal/AIML/blob/master/Convolutional_Network_for_Handwritten_digits_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Covolution Network for Handwritten digits

In [1]:
import tensorflow
from tensorflow.keras import datasets, layers, models

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
(x_train, y_train),(x_test, y_test) = datasets.cifar10.load_data()
print(x_train.shape)
print(y_train.shape)

(50000, 32, 32, 3)
(50000, 1)


In [11]:
print(y_train.shape)
print(y_test.shape)

(50000, 1)
(10000, 1)


Data Preprocessing - Normalization

In [12]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

In [13]:
x_train = x_train / 255
x_test = x_test / 255

In [15]:
y_train[0]

array([6], dtype=uint8)

In [17]:
y_train = y_train.reshape(-1,)

In [19]:
y_train[0]

6

In [20]:
y_test = y_test.reshape(-1,)

Build ANN and check accuracy

In [33]:
ann = models.Sequential([
    layers.Flatten(input_shape=(32,32,3)),
    layers.Dense(3000, activation='relu'),
    layers.Dense(1000, activation='relu'),
     layers.Dense(800, activation='relu'),
    layers.Dense(10, activation='sigmoid')
])

ann.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
ann.fit(x_train, y_train, epochs = 5)

Epoch 1/5
1563/1563 [==============================] - 301s 192ms/step - loss: 1.8906 - accuracy: 0.3145
Epoch 2/5
1563/1563 [==============================] - 303s 194ms/step - loss: 1.6806 - accuracy: 0.3982
Epoch 3/5
1563/1563 [==============================] - 295s 189ms/step - loss: 1.6063 - accuracy: 0.4245
Epoch 4/5
1563/1563 [==============================] - 296s 189ms/step - loss: 1.5464 - accuracy: 0.4455
Epoch 5/5
1563/1563 [==============================] - 293s 187ms/step - loss: 1.5052 - accuracy: 0.4598


In [34]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred = ann.predict(x_test)

313/313 [==============================] - 8s 25ms/step


In [35]:
y_pred[0]

array([0.228896  , 0.18184508, 0.27901673, 0.8283174 , 0.32304892,
       0.79754555, 0.59348434, 0.07659575, 0.52147   , 0.11812758],
      dtype=float32)

In [36]:
np.argmax(y_pred[0])

3

In [37]:
classes[np.argmax(y_pred[0])]

'cat'

In [38]:
y_test[0]

3

In [39]:
classes[y_test[0]]

'cat'

In [40]:
y_pred_classes = [np.argmax(element) for element in y_pred]

print("classification report", classification_report(y_test, y_pred_classes))

classification report               precision    recall  f1-score   support

           0       0.58      0.46      0.51      1000
           1       0.61      0.58      0.59      1000
           2       0.33      0.33      0.33      1000
           3       0.36      0.29      0.32      1000
           4       0.43      0.36      0.39      1000
           5       0.38      0.34      0.36      1000
           6       0.43      0.63      0.51      1000
           7       0.57      0.47      0.52      1000
           8       0.46      0.76      0.57      1000
           9       0.59      0.44      0.50      1000

    accuracy                           0.47     10000
   macro avg       0.47      0.47      0.46     10000
weighted avg       0.47      0.47      0.46     10000



Now let us build a convolutional neural network to train our images

In [42]:
cnn = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3,3), activation='relu',input_shape=(32,32, 3)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [43]:
cnn.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [44]:
cnn.fit(x_train, y_train, epochs=5)

Epoch 1/5
1563/1563 [==============================] - 67s 42ms/step - loss: 1.4688 - accuracy: 0.4660
Epoch 2/5
1563/1563 [==============================] - 64s 41ms/step - loss: 1.0997 - accuracy: 0.6117
Epoch 3/5
1563/1563 [==============================] - 65s 41ms/step - loss: 0.9663 - accuracy: 0.6646
Epoch 4/5
1563/1563 [==============================] - 65s 41ms/step - loss: 0.8755 - accuracy: 0.6970
Epoch 5/5
1563/1563 [==============================] - 64s 41ms/step - loss: 0.8021 - accuracy: 0.7203


In [45]:
cnn.evaluate(x_test, y_test)

313/313 [==============================] - 5s 15ms/step - loss: 0.9318 - accuracy: 0.6820


[0.9317593574523926, 0.6819999814033508]

In [46]:
y_pred = cnn.predict(x_test)

313/313 [==============================] - 4s 13ms/step


In [47]:
y_pred[0]

array([2.4563726e-04, 3.8396513e-05, 4.0923716e-03, 7.5858164e-01,
       1.8932925e-03, 2.9442195e-02, 1.8162556e-01, 1.3740225e-04,
       2.3532864e-02, 4.1064611e-04], dtype=float32)

In [50]:
y_pred_classes = [np.argmax(element) for element in y_pred]

In [63]:
y_pred_classes[:10]

[3, 8, 8, 0, 6, 6, 1, 6, 3, 1]

In [60]:
classes[y_pred_classes[4]]

'frog'

In [61]:
classes[y_test[4]]

'frog'

In [64]:
y_test[:10]

array([3, 8, 8, 0, 6, 6, 1, 6, 3, 1], dtype=uint8)